services:
  - type: web
    name: contactshub-frontend
    runtime: static
    rootDir: contacts-react
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /assets/*.css
        name: Content-Type
        value: text/css
      - path: /assets/*.js
        name: Content-Type
        value: application/javascript
